### ISSUE TITLE
Error converting 32 byte array in new release

### ISSUE THREAD

**Issue by charleschege** [fzyzcjy/flutter_rust_bridge#572]
### Describe the bug

After upgrade to 1.37.2, it breaks arrays like
```rust
struct Foo {
    bar: [u8; 32]
}
```
compiling that produces the error from the `bridge_generated.rs` file:
```
the trait `Wire2Api<[u8; 32]>` is not implemented for `*mut wire_uint_8_list`
```

### Codegen logs with `RUST_LOG=debug` environment variable

```shell
error[E0277]: the trait bound `*mut wire_uint_8_list: Wire2Api<[u8; 32]>` is not satisfied
   --> NativeUI/src/bridge_generated.rs:159:39
    |
159 |             wallet_id: self.wallet_id.wire2api(),
    |                                       ^^^^^^^^ the trait `Wire2Api<[u8; 32]>` is not implemented for `*mut wire_uint_8_list`
    |
    = help: the following other types implement trait `Wire2Api<T>`:
              <*mut wire_uint_8_list as Wire2Api<String>>
              <*mut wire_uint_8_list as Wire2Api<Vec<u8>>>

For more information about this error, try `rustc --explain E0277`.
error: could not compile `my_crate` due to previous error
```

### To Reproduce

Create a struct with [u8; 32] as a field and call it from a function

### OS

Ubuntu 20.05

### Version of `flutter_rust_bridge_codegen`

1.37.2

### Flutter info

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on KDE neon User - 5.25 5.4.0-121-generic, locale en_GB.UTF-8)
Checking Android licenses is taking an unexpectedly long time...[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] VS Code (version 1.69.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 1 category.
```

### Version of `clang++`

10.0.0-4ubuntu1

### Version of `ffigen`

 6.0.1

**Comment by fzyzcjy** [comment]
So, what is the last version that it worked?
